version: "3"
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    ports:
      - 8090:8090
      - 8091:8091/tcp
      - 8091:8091/udp
  basicrobot23:
    image: docker.io/natbodocker/basicrobot23:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv
  coldstorage:
    image: hjcsteve/coldstorageservice:3.0
    network_mode: "host"
    depends_on:
      - basicrobot23
  accessgui:
    image: hjcsteve/accessgui:1.0
    network_mode: "host"
    depends_on:
      - coldstorage
  statusgui:
    image: hjcsteve/statusgui:1.0
    network_mode: "host"
    depends_on:
      - coldstorage
